run:
  tests: true
  build-tags:
    - bench
    - !bench

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    
linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/trb1maker/otus_golang_home_work
          - github.com/google/uuid
          - github.com/stretchr/testify/require
          - github.com/jackc/pgx
          - github.com/go-yaml/yaml
          - github.com/jmoiron/sqlx
          - github.com/mattn/go-sqlite3

  go-critic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
